---
- name: create group for emby
  group:
    name: "{{ group }}"
    gid: "{{ group_id }}"
    system: "{{ system }}"
    state: present
  become: yes

- name: create user for emby
  user:
    name: "{{ user }}"
    uid: "{{ user_id }}"
    group: "{{ group }}"
    groups: "{{ extra_groups }}"
    home: "{{ home_dir }}"
    system: "{{ system }}"
    shell: /bin/false
    state: present
  become: yes

- name: get emby user ID
  command: id -u {{ user | quote }}
  register: emby_user_id
  changed_when: False

- set_fact: emby_user_id={{ emby_user_id.stdout }}

- name: get emby group ID
  command: id -g {{ user | quote }}
  register: emby_group_id
  changed_when: False

- set_fact: emby_group_id={{ emby_group_id.stdout }}

#docker run -d --restart unless-stopped --volume /home/emby:/config --volume /mnt/tv:/mnt/tv --volume /mnt/films:/mnt/films --publish 8096:8096 --publish 8920:8920 --env UID=108 --env GID=111 --name emby emby/embyserver:latest
- name: setup docker container
  docker_container:
    name: emby
    image: emby/embyserver:latest
    volumes:
      - "{{ config_dir }}:/config"
      # TODO: make these configurable
      - /mnt/tv:/mnt/tv
      - /mnt/films:/mnt/films
    published_ports:
      - 8096:8096
      - 8920:8920
    env:
      UID: "{{ emby_user_id }}"
      GID: "{{ emby_group_id }}"
    restart_policy: unless-stopped
    pull: "{{ pull | default('no')  }}"
    # networks_cli_compatible: yes
