---
## TODO: Rename "setup" role to "system"?
- import_tasks: install-sudo.yml

- name: Update and upgrade system.
  apt:
    update_cache: yes
    upgrade: yes
  become: yes
##

## TODO: Move this to my docker role
- name: Install dependencies.
  apt:
    name:
      - python3-setuptools
      - python3-pip
  become: yes

- name: Install pip3 packages.
  pip:
    name:
      - docker
      - docker-compose
    # TODO: This doesn't seem to have any effect. Need the ansible_python_interpreter var to be set.
    executable: /usr/bin/pip3

- name: Install docker-ce.
  import_role:
    name: geerlingguy.docker
  vars:
    docker_apt_ignore_key_error: false
    docker_install_compose: false
    docker_users:
      - "{{ docker_user | default(ansible_env.SUDO_USER) | default(ansible_env.USER) }}"
  become: yes
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version|int <= 9

# TODO: Install docker.io if Debian >= 10
# TODO: Install docker snap if Ubuntu
##
